// Generated by scripts/generate-ipd-bridges.mjs. Edit src/environment/bridge instead.

// packages/ipd/src/environment/bridge/launch.ts
import { spawn } from "node:child_process";
import { mkdir, open } from "node:fs/promises";
import { dirname } from "node:path";
async function launchCommand(launch, emit, detached = false) {
  if (launch.logPath) await mkdir(dirname(launch.logPath), { recursive: true });
  const log = launch.logPath ? await open(launch.logPath, "w", 384) : void 0;
  const marker = Buffer.from("\n[Output truncated at the environment log limit]\n").subarray(0, launch.maxLogBytes);
  let remaining = log ? Math.max(0, launch.maxLogBytes - marker.length) : 0;
  let truncated = false;
  const child = spawn(launch.argv[0], launch.argv.slice(1), {
    cwd: launch.cwd,
    env: launch.environment,
    stdio: ["inherit", "pipe", "pipe"],
    detached
  });
  let writes = Promise.resolve();
  const collect = (data, stream) => {
    if (emit && !stream.write(data)) {
      const input = stream === process.stdout ? child.stdout : child.stderr;
      input.pause();
      stream.once("drain", () => input.resume());
    }
    if (log) {
      const chunk = data.subarray(0, remaining);
      remaining -= chunk.length;
      if (chunk.length)
        writes = writes.then(async () => {
          await log.write(chunk);
        });
      if (data.length > chunk.length && !truncated) {
        truncated = true;
        writes = writes.then(async () => {
          await log.write(marker);
        });
      }
      void writes.catch(() => child.kill("SIGKILL"));
    }
  };
  child.stdout.on("data", (data) => collect(data, process.stdout));
  child.stderr.on("data", (data) => collect(data, process.stderr));
  const exited = new Promise((resolve, reject) => {
    child.once("error", reject);
    child.once("close", (code) => resolve(code ?? 1));
  }).finally(async () => {
    try {
      await writes;
    } finally {
      await log?.close();
    }
  });
  void exited.catch(() => {
  });
  await new Promise((resolve, reject) => {
    child.once("spawn", resolve);
    child.once("error", reject);
  });
  return { child, exited };
}

// packages/ipd/src/environment/bridge/protocol.ts
var BRIDGE_VERSION = 1;
function absolute(value) {
  return typeof value === "string" && value.startsWith("/") && !value.includes("\0") && !value.split("/").includes("..");
}
function decodeBridgeRequest(raw) {
  const request = JSON.parse(raw);
  if (!request || typeof request !== "object") throw new Error("Invalid bridge request");
  const value = request;
  if (value.version !== BRIDGE_VERSION) throw new Error("Unsupported bridge protocol version");
  if (["start", "run", "status", "stop", "cancel_command"].includes(String(value.operation)) || value.operation === "exec" && value.processId !== void 0) {
    if (!absolute(value.scratch) || typeof value.processId !== "string" || !/^[a-f0-9-]{36}$/.test(value.processId))
      throw new Error("Invalid managed process identity");
  } else if (["read", "write", "list", "stat", "mkdir", "search", "find"].includes(String(value.operation))) {
    if (!absolute(value.path)) throw new Error("Invalid bridge file path");
    if (["search", "find"].includes(String(value.operation)) && (typeof value.pattern !== "string" || value.maxResults !== void 0 && (!Number.isInteger(value.maxResults) || Number(value.maxResults) < 1 || Number(value.maxResults) > 1e4)))
      throw new Error("Invalid search request");
    if (value.offset !== void 0 && (!Number.isSafeInteger(value.offset) || Number(value.offset) < 0))
      throw new Error("Invalid file offset");
    if (value.length !== void 0 && (!Number.isSafeInteger(value.length) || Number(value.length) < 1 || Number(value.length) > 1048576))
      throw new Error("Invalid file page length");
  } else if (value.operation !== "hello" && value.operation !== "exec") throw new Error("Unknown bridge operation");
  if (["exec", "start", "run"].includes(String(value.operation))) {
    const launch = value.launch;
    if (!launch || !Array.isArray(launch.argv) || launch.argv.length === 0 || launch.argv.some((arg) => typeof arg !== "string" || arg.includes("\0")) || !launch.argv[0] || !absolute(launch.cwd) || !Number.isInteger(launch.maxLogBytes) || launch.maxLogBytes < 1)
      throw new Error("Invalid command launch");
    if (!launch.environment || typeof launch.environment !== "object" || Array.isArray(launch.environment) || Object.entries(launch.environment).some(
      ([key, val]) => !/^[A-Za-z_][A-Za-z0-9_]*$/.test(key) || typeof val !== "string" || val.includes("\0")
    ))
      throw new Error("Invalid command environment");
    if (launch.logPath !== void 0 && !absolute(launch.logPath)) throw new Error("Invalid command log path");
  }
  return value;
}

// packages/ipd/src/environment/bridge/command-control.ts
import { mkdir as mkdir2, readdir, readFile, rename, writeFile } from "node:fs/promises";
import { setTimeout as delay } from "node:timers/promises";
async function groupAlive(pid) {
  for (const entry of await readdir("/proc")) {
    if (!/^\d+$/.test(entry)) continue;
    try {
      const stat = await readFile(`/proc/${entry}/stat`, "utf8");
      const fields = stat.slice(stat.lastIndexOf(")") + 2).split(" ");
      if (Number(fields[2]) === pid && fields[0] !== "Z" && fields[0] !== "X") return true;
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
  }
  return false;
}
async function stopGroup(pid) {
  try {
    process.kill(-pid, "SIGKILL");
  } catch (error) {
    if (error.code !== "ESRCH") throw error;
  }
  const deadline = Date.now() + 3e3;
  while (await groupAlive(pid)) {
    if (Date.now() > deadline) throw new Error("Command process group did not stop");
    await delay(20);
  }
}
async function controlledCommand(scratch, id, launch) {
  const root = `${scratch}/.ipd-commands`;
  await mkdir2(root, { recursive: true });
  const prefix = `${root}/${id}`;
  const complete = async (value) => {
    await writeFile(`${prefix}.done.tmp`, JSON.stringify(value));
    await rename(`${prefix}.done.tmp`, `${prefix}.done`);
  };
  if (!launch) {
    await writeFile(`${prefix}.cancel`, "cancelled", { flag: "wx" }).catch((error) => {
      if (error.code !== "EEXIST") throw error;
    });
    const deadline = Date.now() + 5e3;
    while (Date.now() < deadline) {
      try {
        const completed = JSON.parse(await readFile(`${prefix}.done`, "utf8"));
        if (completed.pid && !completed.stopped) await stopGroup(completed.pid);
        return 0;
      } catch (error) {
        if (error.code !== "ENOENT") throw error;
      }
      await delay(20);
    }
    throw new Error("Command cancellation was not acknowledged");
  }
  let stopping;
  const cancelled = async () => {
    try {
      await readFile(`${prefix}.cancel`);
      return true;
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
      return false;
    }
  };
  if (await cancelled()) {
    await complete({ stopped: true });
    return 130;
  }
  const launched = await launchCommand(launch, true, true);
  const pid = launched.child.pid;
  const timer = setInterval(() => {
    void cancelled().then((value) => {
      if (value) stopping ??= stopGroup(pid);
    }).catch(() => {
      stopping ??= stopGroup(pid);
    });
    void stopping?.catch(() => {
    });
  }, 25);
  try {
    const exitCode = await launched.exited;
    const requested = await cancelled();
    if (stopping) await stopping;
    else if (requested) await stopGroup(pid);
    await complete({ pid, stopped: Boolean(stopping) || requested });
    return exitCode;
  } finally {
    clearInterval(timer);
  }
}

// packages/ipd/src/environment/bridge/command.ts
process.stdout.on("error", () => {
});
process.stderr.on("error", () => {
});
try {
  const request = decodeBridgeRequest(process.argv[2] ?? "");
  if (request.operation === "hello")
    process.stdout.write(JSON.stringify({ version: BRIDGE_VERSION, commandCancellation: true }));
  else if (request.operation === "cancel_command") {
    await controlledCommand(request.scratch, request.processId);
    process.stdout.write(JSON.stringify({ stopped: true }));
  } else if (request.operation === "exec")
    process.exitCode = request.processId && request.scratch ? await controlledCommand(request.scratch, request.processId, request.launch) : await (await launchCommand(request.launch, true)).exited;
  else throw new Error("Command bridge only accepts exec or hello");
} catch (error) {
  process.stderr.write(
    JSON.stringify({
      bridgeError: {
        code: error.code ?? "BRIDGE_ERROR",
        message: error instanceof Error ? error.message : String(error)
      }
    })
  );
  process.exitCode = 1;
}
