// Generated by scripts/generate-ipd-bridges.mjs. Edit src/environment/bridge instead.

// packages/ipd/src/environment/bridge/launch.ts
import { spawn } from "node:child_process";
import { mkdir, open } from "node:fs/promises";
import { dirname } from "node:path";
async function launchCommand(launch, emit) {
  if (launch.logPath) await mkdir(dirname(launch.logPath), { recursive: true });
  const log = launch.logPath ? await open(launch.logPath, "w", 384) : void 0;
  const marker = Buffer.from("\n[Output truncated at the environment log limit]\n").subarray(0, launch.maxLogBytes);
  let remaining = log ? Math.max(0, launch.maxLogBytes - marker.length) : 0;
  let truncated = false;
  const child = spawn(launch.argv[0], launch.argv.slice(1), {
    cwd: launch.cwd,
    env: launch.environment,
    stdio: ["inherit", "pipe", "pipe"]
  });
  let writes = Promise.resolve();
  const collect = (data, stream) => {
    if (emit && !stream.write(data)) {
      const input = stream === process.stdout ? child.stdout : child.stderr;
      input.pause();
      stream.once("drain", () => input.resume());
    }
    if (log) {
      const chunk = data.subarray(0, remaining);
      remaining -= chunk.length;
      if (chunk.length)
        writes = writes.then(async () => {
          await log.write(chunk);
        });
      if (data.length > chunk.length && !truncated) {
        truncated = true;
        writes = writes.then(async () => {
          await log.write(marker);
        });
      }
      void writes.catch(() => child.kill("SIGKILL"));
    }
  };
  child.stdout.on("data", (data) => collect(data, process.stdout));
  child.stderr.on("data", (data) => collect(data, process.stderr));
  const exited = new Promise((resolve, reject) => {
    child.once("error", reject);
    child.once("close", (code) => resolve(code ?? 1));
  }).finally(async () => {
    try {
      await writes;
    } finally {
      await log?.close();
    }
  });
  void exited.catch(() => {
  });
  await new Promise((resolve, reject) => {
    child.once("spawn", resolve);
    child.once("error", reject);
  });
  return { child, exited };
}

// packages/ipd/src/environment/bridge/protocol.ts
var BRIDGE_VERSION = 1;
function absolute(value) {
  return typeof value === "string" && value.startsWith("/") && !value.includes("\0") && !value.split("/").includes("..");
}
function decodeBridgeRequest(raw) {
  const request = JSON.parse(raw);
  if (!request || typeof request !== "object") throw new Error("Invalid bridge request");
  const value = request;
  if (value.version !== BRIDGE_VERSION) throw new Error("Unsupported bridge protocol version");
  if (["start", "run", "status", "stop"].includes(String(value.operation))) {
    if (!absolute(value.scratch) || typeof value.processId !== "string" || !/^[a-f0-9-]{36}$/.test(value.processId))
      throw new Error("Invalid managed process identity");
  } else if (["read", "write", "list", "stat", "mkdir"].includes(String(value.operation))) {
    if (!absolute(value.path)) throw new Error("Invalid bridge file path");
    if (value.offset !== void 0 && (!Number.isSafeInteger(value.offset) || Number(value.offset) < 0))
      throw new Error("Invalid file offset");
    if (value.length !== void 0 && (!Number.isSafeInteger(value.length) || Number(value.length) < 1 || Number(value.length) > 1048576))
      throw new Error("Invalid file page length");
  } else if (value.operation !== "hello" && value.operation !== "exec") throw new Error("Unknown bridge operation");
  if (["exec", "start", "run"].includes(String(value.operation))) {
    const launch = value.launch;
    if (!launch || !Array.isArray(launch.argv) || launch.argv.length === 0 || launch.argv.some((arg) => typeof arg !== "string" || arg.includes("\0")) || !launch.argv[0] || !absolute(launch.cwd) || !Number.isInteger(launch.maxLogBytes) || launch.maxLogBytes < 1)
      throw new Error("Invalid command launch");
    if (!launch.environment || typeof launch.environment !== "object" || Array.isArray(launch.environment) || Object.entries(launch.environment).some(
      ([key, val]) => !/^[A-Za-z_][A-Za-z0-9_]*$/.test(key) || typeof val !== "string" || val.includes("\0")
    ))
      throw new Error("Invalid command environment");
    if (launch.logPath !== void 0 && !absolute(launch.logPath)) throw new Error("Invalid command log path");
  }
  return value;
}

// packages/ipd/src/environment/bridge/command.ts
try {
  const request = decodeBridgeRequest(process.argv[2] ?? "");
  if (request.operation === "hello") process.stdout.write(JSON.stringify({ version: BRIDGE_VERSION }));
  else if (request.operation === "exec") process.exitCode = await (await launchCommand(request.launch, true)).exited;
  else throw new Error("Command bridge only accepts exec or hello");
} catch (error) {
  process.stderr.write(
    JSON.stringify({
      bridgeError: {
        code: error.code ?? "BRIDGE_ERROR",
        message: error instanceof Error ? error.message : String(error)
      }
    })
  );
  process.exitCode = 1;
}
