// Generated by scripts/generate-ipd-bridges.mjs. Edit src/environment/bridge instead.

// packages/ipd/src/environment/bridge/egress.ts
import { createServer, request } from "node:http";
import { connect, Socket } from "node:net";

// packages/ipd/src/environment/egress-policy.ts
import { resolve4 } from "node:dns/promises";
import { isIPv4 } from "node:net";
function publicAddress(address) {
  if (!isIPv4(address)) return false;
  const [a, b, c] = address.split(".").map(Number);
  return !(a === 0 || a === 10 || a === 127 || a >= 224 || a === 100 && b >= 64 && b <= 127 || a === 169 && b === 254 || a === 172 && b >= 16 && b <= 31 || a === 192 && [0, 168].includes(b) || a === 192 && b === 88 && c === 99 || a === 198 && [18, 19].includes(b) || a === 198 && b === 51 && c === 100 || a === 203 && b === 0 && c === 113);
}
async function resolveDestination(raw, hosts, denied, lookup = resolve4) {
  const url = new URL(raw);
  if (!["http:", "https:"].includes(url.protocol) || url.username || url.password || url.port && url.port !== (url.protocol === "https:" ? "443" : "80"))
    throw new Error("Destination protocol or port denied");
  const hostname = url.hostname.toLowerCase();
  if (!hosts.some(
    (host) => host === "*" || hostname === host || host.startsWith("*.") && hostname.endsWith(host.slice(1))
  ))
    throw new Error("Destination host denied");
  if (!hostname.includes(".") || hostname.endsWith(".localhost") || hostname.endsWith(".local"))
    throw new Error("Local destination denied");
  const addresses = isIPv4(hostname) ? [hostname] : await lookup(hostname);
  if (!addresses.length || addresses.some((address) => !publicAddress(address) || denied.includes(address)))
    throw new Error("Non-public destination denied");
  return { url, address: addresses[0] };
}

// packages/ipd/src/environment/bridge/egress.ts
var policy = JSON.parse(process.env.IPD_EGRESS_POLICY ?? "");
var authorization = `Basic ${Buffer.from(`ipd:${policy.token}`).toString("base64")}`;
var server = createServer(async (incoming, response) => {
  try {
    if (incoming.headers["proxy-authorization"] !== authorization) throw new Error("Proxy authentication required");
    const { url, address } = await resolveDestination(incoming.url ?? "", policy.hosts, policy.denied);
    if (url.protocol !== "http:") throw new Error("Use CONNECT for HTTPS");
    const headers = { ...incoming.headers, host: url.host };
    delete headers["proxy-authorization"];
    delete headers["proxy-connection"];
    const upstream = request(
      {
        hostname: address,
        port: 80,
        path: url.pathname + url.search,
        method: incoming.method,
        headers,
        timeout: 6e4
      },
      (reply) => {
        response.writeHead(reply.statusCode ?? 502, reply.headers);
        reply.pipe(response);
      }
    );
    upstream.on("timeout", () => upstream.destroy());
    upstream.on("error", () => response.destroy());
    incoming.on("aborted", () => upstream.destroy());
    response.on("close", () => upstream.destroy());
    incoming.pipe(upstream);
  } catch {
    response.writeHead(403);
    response.end("Egress policy denied the destination");
  }
});
server.on("connect", async (incoming, socket, head) => {
  try {
    if (incoming.headers["proxy-authorization"] !== authorization) throw new Error("Proxy authentication required");
    const { address } = await resolveDestination(`https://${incoming.url}`, policy.hosts, policy.denied);
    const upstream = connect(443, address);
    upstream.setTimeout(6e4, () => upstream.destroy());
    if (socket instanceof Socket) socket.setTimeout(6e4, () => socket.destroy());
    upstream.on("error", () => socket.destroy());
    socket.on("error", () => upstream.destroy());
    socket.on("close", () => upstream.destroy());
    upstream.on("close", () => socket.destroy());
    upstream.once("connect", () => {
      socket.write("HTTP/1.1 200 Connection Established\r\n\r\n");
      if (head.length) upstream.write(head);
      socket.pipe(upstream);
      upstream.pipe(socket);
    });
  } catch {
    socket.end("HTTP/1.1 403 Forbidden\r\nConnection: close\r\n\r\n");
  }
});
server.maxConnections = 128;
server.headersTimeout = 1e4;
server.requestTimeout = 6e4;
server.listen(8080, "0.0.0.0");
