// Generated by scripts/generate-ipd-bridges.mjs. Edit src/environment/bridge instead.

// packages/ipd/src/environment/bridge/fs.ts
import { lstat, mkdir, open, readdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

// packages/ipd/src/environment/bridge/protocol.ts
var BRIDGE_VERSION = 1;
function absolute(value) {
  return typeof value === "string" && value.startsWith("/") && !value.includes("\0") && !value.split("/").includes("..");
}
function decodeBridgeRequest(raw) {
  const request = JSON.parse(raw);
  if (!request || typeof request !== "object") throw new Error("Invalid bridge request");
  const value = request;
  if (value.version !== BRIDGE_VERSION) throw new Error("Unsupported bridge protocol version");
  if (["start", "run", "status", "stop", "cancel_command"].includes(String(value.operation)) || value.operation === "exec" && value.processId !== void 0) {
    if (!absolute(value.scratch) || typeof value.processId !== "string" || !/^[a-f0-9-]{36}$/.test(value.processId))
      throw new Error("Invalid managed process identity");
  } else if (["read", "write", "list", "stat", "mkdir", "search", "find"].includes(String(value.operation))) {
    if (!absolute(value.path)) throw new Error("Invalid bridge file path");
    if (["search", "find"].includes(String(value.operation)) && (typeof value.pattern !== "string" || value.maxResults !== void 0 && (!Number.isInteger(value.maxResults) || Number(value.maxResults) < 1 || Number(value.maxResults) > 1e4)))
      throw new Error("Invalid search request");
    if (value.offset !== void 0 && (!Number.isSafeInteger(value.offset) || Number(value.offset) < 0))
      throw new Error("Invalid file offset");
    if (value.length !== void 0 && (!Number.isSafeInteger(value.length) || Number(value.length) < 1 || Number(value.length) > 1048576))
      throw new Error("Invalid file page length");
  } else if (value.operation !== "hello" && value.operation !== "exec") throw new Error("Unknown bridge operation");
  if (["exec", "start", "run"].includes(String(value.operation))) {
    const launch = value.launch;
    if (!launch || !Array.isArray(launch.argv) || launch.argv.length === 0 || launch.argv.some((arg) => typeof arg !== "string" || arg.includes("\0")) || !launch.argv[0] || !absolute(launch.cwd) || !Number.isInteger(launch.maxLogBytes) || launch.maxLogBytes < 1)
      throw new Error("Invalid command launch");
    if (!launch.environment || typeof launch.environment !== "object" || Array.isArray(launch.environment) || Object.entries(launch.environment).some(
      ([key, val]) => !/^[A-Za-z_][A-Za-z0-9_]*$/.test(key) || typeof val !== "string" || val.includes("\0")
    ))
      throw new Error("Invalid command environment");
    if (launch.logPath !== void 0 && !absolute(launch.logPath)) throw new Error("Invalid command log path");
  }
  return value;
}

// packages/ipd/src/environment/bridge/search.ts
import { spawn } from "node:child_process";
import { createInterface } from "node:readline";
async function searchFiles(request) {
  const args = request.operation === "find" ? [
    "--files",
    "--hidden",
    "--glob",
    request.pattern,
    "--glob",
    "!**/node_modules/**",
    "--glob",
    "!**/.git/**",
    "--",
    request.path
  ] : [
    "--json",
    "--line-number",
    "--max-columns",
    "4096",
    ...request.ignoreCase ? ["--ignore-case"] : [],
    ...request.literal ? ["--fixed-strings"] : [],
    ...request.glob ? ["--glob", request.glob] : [],
    "--",
    request.pattern,
    request.path
  ];
  const child = spawn("rg", args, { stdio: ["ignore", "pipe", "pipe"] });
  const result = [];
  let error = "";
  child.stderr.on("data", (chunk) => {
    error = (error + chunk.toString()).slice(0, 8192);
  });
  const exited = new Promise((resolve, reject) => {
    child.once("error", reject);
    child.once("close", resolve);
  });
  void exited.catch(() => {
  });
  let limited = false;
  let readComplete = false;
  try {
    for await (const line of createInterface({ input: child.stdout, crlfDelay: Infinity })) {
      if (request.operation === "find") result.push(line);
      else {
        const event = JSON.parse(line);
        if (event.type === "match" && event.data?.path?.text)
          result.push({ path: event.data.path.text, line: event.data.line_number, text: event.data.lines?.text });
      }
      if (result.length >= (request.maxResults ?? 1e3)) {
        limited = true;
        break;
      }
    }
    readComplete = true;
  } finally {
    if ((limited || !readComplete) && child.exitCode === null) child.kill("SIGKILL");
  }
  const code = await exited;
  if (!limited && code !== 0 && code !== 1) throw new Error(`Search failed: ${error}`);
  return result;
}

// packages/ipd/src/environment/bridge/fs.ts
try {
  const request = decodeBridgeRequest(process.argv[2] ?? "");
  if (!("path" in request)) throw new Error("File bridge requires a file operation");
  const { operation, path } = request;
  if (operation === "read") {
    if (request.length === void 0) {
      const file = await open(path, "r");
      try {
        if ((await file.stat()).size > 64 * 1024 * 1024)
          throw Object.assign(
            new Error("File exceeds the 64 MiB read transport limit; inspect a smaller extract with Bash"),
            { code: "OUTPUT_LIMIT" }
          );
        process.stdout.write(await file.readFile());
      } finally {
        await file.close();
      }
    } else {
      const file = await open(path, "r");
      try {
        const buffer = Buffer.alloc(request.length);
        const { bytesRead } = await file.read(buffer, 0, buffer.length, request.offset ?? 0);
        process.stdout.write(buffer.subarray(0, bytesRead));
      } finally {
        await file.close();
      }
    }
  } else if (operation === "search" || operation === "find") {
    process.stdout.write(JSON.stringify(await searchFiles(request)));
  } else if (operation === "write") {
    const chunks = [];
    for await (const chunk of process.stdin) chunks.push(chunk);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, Buffer.concat(chunks), { mode: 384 });
  } else if (operation === "mkdir") await mkdir(path, { recursive: true });
  else if (operation === "stat") {
    const stat = await lstat(path);
    process.stdout.write(
      JSON.stringify({
        type: stat.isDirectory() ? "directory" : stat.isSymbolicLink() ? "symlink" : "file",
        size: stat.size
      })
    );
  } else {
    const entries = await Promise.all(
      (await readdir(path, { withFileTypes: true })).map(async (entry) => ({
        name: entry.name,
        type: entry.isDirectory() ? "directory" : entry.isSymbolicLink() ? "symlink" : "file",
        size: (await lstat(`${path}/${entry.name}`)).size
      }))
    );
    process.stdout.write(JSON.stringify(entries));
  }
} catch (error) {
  process.stderr.write(
    JSON.stringify({
      bridgeError: {
        code: error.code ?? "BRIDGE_ERROR",
        message: error instanceof Error ? error.message : String(error)
      }
    })
  );
  process.exitCode = 1;
}
