// Generated by scripts/generate-ipd-bridges.mjs. Edit src/environment/bridge instead.

// packages/ipd/src/environment/bridge/process.ts
import { fork } from "node:child_process";
import { randomUUID } from "node:crypto";
import { closeSync, openSync } from "node:fs";
import { mkdir as mkdir2, readFile, rename, writeFile } from "node:fs/promises";
import { setTimeout as delay } from "node:timers/promises";
import { fileURLToPath } from "node:url";

// packages/ipd/src/environment/bridge/launch.ts
import { spawn } from "node:child_process";
import { mkdir, open } from "node:fs/promises";
import { dirname } from "node:path";
async function launchCommand(launch, emit) {
  if (launch.logPath) await mkdir(dirname(launch.logPath), { recursive: true });
  const log = launch.logPath ? await open(launch.logPath, "w", 384) : void 0;
  const marker = Buffer.from("\n[Output truncated at the environment log limit]\n").subarray(0, launch.maxLogBytes);
  let remaining = log ? Math.max(0, launch.maxLogBytes - marker.length) : 0;
  let truncated = false;
  const child = spawn(launch.argv[0], launch.argv.slice(1), {
    cwd: launch.cwd,
    env: launch.environment,
    stdio: ["inherit", "pipe", "pipe"]
  });
  let writes = Promise.resolve();
  const collect = (data, stream) => {
    if (emit && !stream.write(data)) {
      const input = stream === process.stdout ? child.stdout : child.stderr;
      input.pause();
      stream.once("drain", () => input.resume());
    }
    if (log) {
      const chunk = data.subarray(0, remaining);
      remaining -= chunk.length;
      if (chunk.length)
        writes = writes.then(async () => {
          await log.write(chunk);
        });
      if (data.length > chunk.length && !truncated) {
        truncated = true;
        writes = writes.then(async () => {
          await log.write(marker);
        });
      }
      void writes.catch(() => child.kill("SIGKILL"));
    }
  };
  child.stdout.on("data", (data) => collect(data, process.stdout));
  child.stderr.on("data", (data) => collect(data, process.stderr));
  const exited = new Promise((resolve, reject) => {
    child.once("error", reject);
    child.once("close", (code) => resolve(code ?? 1));
  }).finally(async () => {
    try {
      await writes;
    } finally {
      await log?.close();
    }
  });
  void exited.catch(() => {
  });
  await new Promise((resolve, reject) => {
    child.once("spawn", resolve);
    child.once("error", reject);
  });
  return { child, exited };
}

// packages/ipd/src/environment/bridge/protocol.ts
var BRIDGE_VERSION = 1;
function absolute(value) {
  return typeof value === "string" && value.startsWith("/") && !value.includes("\0") && !value.split("/").includes("..");
}
function decodeBridgeRequest(raw) {
  const request2 = JSON.parse(raw);
  if (!request2 || typeof request2 !== "object") throw new Error("Invalid bridge request");
  const value = request2;
  if (value.version !== BRIDGE_VERSION) throw new Error("Unsupported bridge protocol version");
  if (["start", "run", "status", "stop"].includes(String(value.operation))) {
    if (!absolute(value.scratch) || typeof value.processId !== "string" || !/^[a-f0-9-]{36}$/.test(value.processId))
      throw new Error("Invalid managed process identity");
  } else if (["read", "write", "list", "stat", "mkdir"].includes(String(value.operation))) {
    if (!absolute(value.path)) throw new Error("Invalid bridge file path");
    if (value.offset !== void 0 && (!Number.isSafeInteger(value.offset) || Number(value.offset) < 0))
      throw new Error("Invalid file offset");
    if (value.length !== void 0 && (!Number.isSafeInteger(value.length) || Number(value.length) < 1 || Number(value.length) > 1048576))
      throw new Error("Invalid file page length");
  } else if (value.operation !== "hello" && value.operation !== "exec") throw new Error("Unknown bridge operation");
  if (["exec", "start", "run"].includes(String(value.operation))) {
    const launch = value.launch;
    if (!launch || !Array.isArray(launch.argv) || launch.argv.length === 0 || launch.argv.some((arg) => typeof arg !== "string" || arg.includes("\0")) || !launch.argv[0] || !absolute(launch.cwd) || !Number.isInteger(launch.maxLogBytes) || launch.maxLogBytes < 1)
      throw new Error("Invalid command launch");
    if (!launch.environment || typeof launch.environment !== "object" || Array.isArray(launch.environment) || Object.entries(launch.environment).some(
      ([key, val]) => !/^[A-Za-z_][A-Za-z0-9_]*$/.test(key) || typeof val !== "string" || val.includes("\0")
    ))
      throw new Error("Invalid command environment");
    if (launch.logPath !== void 0 && !absolute(launch.logPath)) throw new Error("Invalid command log path");
  }
  return value;
}
function encodeBridgeRequest(request2) {
  const raw = JSON.stringify(request2);
  decodeBridgeRequest(raw);
  return raw;
}

// packages/ipd/src/environment/bridge/process.ts
var START_TIMEOUT_MS = 1e4;
var request = decodeBridgeRequest(process.argv[2] ?? "");
if (!("scratch" in request)) throw new Error("Process bridge requires a managed process request");
var { scratch, processId } = request;
var root = `${scratch}/.ipd-processes`;
var metadataPath = `${root}/${processId}.json`;
var logPath = `${root}/${processId}.log`;
await mkdir2(root, { recursive: true });
var metadata = async () => JSON.parse(await readFile(metadataPath, "utf8"));
async function saveMetadata(value) {
  const temporary = `${metadataPath}.${randomUUID()}.tmp`;
  await writeFile(temporary, JSON.stringify(value), { mode: 384 });
  await rename(temporary, metadataPath);
}
function signalGroup(pid, signal) {
  if (!pid) return false;
  try {
    process.kill(-pid, signal);
    return true;
  } catch (error) {
    if (error.code !== "ESRCH") throw error;
    return false;
  }
}
if (request.operation === "start") {
  const log = openSync(logPath, "a", 384);
  const runner = fork(
    fileURLToPath(import.meta.url),
    [encodeBridgeRequest({ ...request, operation: "run", launch: { ...request.launch, logPath } })],
    {
      detached: true,
      execArgv: [],
      stdio: ["ignore", log, log, "ipc"]
    }
  );
  closeSync(log);
  try {
    await new Promise((resolve, reject) => {
      let finished = false;
      const finish = (error) => {
        if (finished) return;
        finished = true;
        clearTimeout(timer);
        runner.off("error", onError);
        runner.off("exit", onExit);
        runner.off("disconnect", onDisconnect);
        runner.off("message", onMessage);
        if (error) reject(error);
        else resolve();
      };
      const onError = (error) => finish(error);
      const onExit = (code, signal) => finish(new Error(`Runner exited before acknowledgement (${code ?? signal})`));
      const onDisconnect = () => finish(new Error("Runner disconnected before acknowledgement"));
      const onMessage = (message) => {
        if (message?.version !== BRIDGE_VERSION || message.processId !== processId)
          return finish(new Error("Invalid managed process acknowledgement"));
        if (message.type === "failed") return finish(new Error(message.message));
        if (message.type !== "ready" || message.pid !== runner.pid)
          return finish(new Error("Invalid managed process acknowledgement"));
        runner.send({ version: BRIDGE_VERSION, type: "accepted", processId }, (error) => finish(error));
      };
      const timer = setTimeout(() => finish(new Error("Managed process startup timed out")), START_TIMEOUT_MS);
      runner.once("error", onError);
      runner.once("exit", onExit);
      runner.once("disconnect", onDisconnect);
      runner.once("message", onMessage);
    });
    if (runner.connected) runner.disconnect();
    runner.unref();
    process.stdout.write(JSON.stringify({ version: BRIDGE_VERSION, pid: runner.pid }));
  } catch (error) {
    signalGroup(runner.pid, "SIGKILL");
    if (runner.connected) runner.disconnect();
    const message = error instanceof Error ? error.message : String(error);
    await saveMetadata({ pid: runner.pid ?? 0, state: "exited", exitCode: -1, error: message });
    throw new Error(`Managed process ${processId} failed to start: ${message}; log: ${logPath}`, { cause: error });
  }
} else if (request.operation === "run") {
  if (!process.connected) throw new Error("Managed runner requires a start handshake");
  const orphaned = () => {
    signalGroup(process.pid, "SIGKILL");
  };
  process.once("disconnect", orphaned);
  const accepted = new Promise((resolve) => {
    process.once("message", (message) => {
      if (message?.version !== BRIDGE_VERSION || message.type !== "accepted" || message.processId !== processId)
        return orphaned();
      process.off("disconnect", orphaned);
      resolve();
    });
  });
  try {
    const launched = await launchCommand(request.launch, false);
    await saveMetadata({ pid: process.pid, state: "running" });
    await new Promise((resolve, reject) => {
      process.send(
        { version: BRIDGE_VERSION, type: "ready", processId, pid: process.pid },
        (error) => error ? reject(error) : resolve()
      );
    });
    await accepted;
    await saveMetadata({ pid: process.pid, state: "exited", exitCode: await launched.exited });
  } catch (error) {
    console.error(error);
    if (process.connected)
      process.send(
        {
          version: BRIDGE_VERSION,
          type: "failed",
          processId,
          message: error instanceof Error ? error.message : String(error)
        },
        (sendError) => {
          if (sendError) orphaned();
        }
      );
    else orphaned();
  }
} else if (request.operation === "status") {
  const current = await metadata();
  if (current.state === "running" && !signalGroup(current.pid, 0)) {
    current.state = "exited";
    await saveMetadata(current);
  }
  process.stdout.write(JSON.stringify(current));
} else if (request.operation === "stop") {
  const current = await metadata();
  let killed = false;
  if (current.state === "running") {
    signalGroup(current.pid, "SIGTERM");
    await delay(250);
    killed = signalGroup(current.pid, "SIGKILL");
    current.state = "stopped";
    await saveMetadata(current);
  }
  process.stdout.write(JSON.stringify({ ...current, killed }));
}
